const CHAT_API_FREQUENCY_PENALTY = 0;
const CHAT_API_MAX_TOKENS = 1024;
const CHAT_API_PRESENCE_PENALTY = 0;
const CHAT_API_TEMPERATURE = 0.5;
const CHAT_API_TOP_P = 0;

export {
  CHAT_API_FREQUENCY_PENALTY,
  CHAT_API_MAX_TOKENS,
  CHAT_API_PRESENCE_PENALTY,
  CHAT_API_TEMPERATURE,
  CHAT_API_TOP_P,
};
