const MAGIC_NUMBER_FAHRENHEIT_CORRECTION = 32;
const MAGIC_NUMBER_FAHRENHEIT_MULTIPLIER = 9 / 5;
const MAGIC_NUMBER_METERS_PER_SECOND_TO_KILOMETERS_PER_HOUR = 3.6;
const MAGIC_NUMBER_METERS_PER_SECOND_TO_MILES_PER_HOUR = 2.237;

export {
  MAGIC_NUMBER_FAHRENHEIT_CORRECTION,
  MAGIC_NUMBER_FAHRENHEIT_MULTIPLIER,
  MAGIC_NUMBER_METERS_PER_SECOND_TO_KILOMETERS_PER_HOUR,
  MAGIC_NUMBER_METERS_PER_SECOND_TO_MILES_PER_HOUR,
};
