//  games
const PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORS = '/games/rock-paper-scissors';
const PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORSLIZARDSPOCK =
  '/games/rock-paper-scissors-lizard-spock';
//  job hunting
const PUBLIC_ROUTE_PAGE_JOB_HUNTING_JAT =
  '/job-hunting/job-application-tracking';
//  legal
const PUBLIC_ROUTE_PAGE_COOKIES = '/legal/cookies';
const PUBLIC_ROUTE_PAGE_PRIVACY = '/legal/privacy';
const PUBLIC_ROUTE_PAGE_TERMS = '/legal/terms';
//  root
const PUBLIC_ROUTE_PAGE_ABOUT = '/about';
const PUBLIC_ROUTE_PAGE_AUTHENTICATE = '/authenticate';
const PUBLIC_ROUTE_PAGE_HOME = '/';
const PUBLIC_ROUTE_PAGE_PRICING = '/pricing';
const PUBLIC_ROUTE_PAGE_REFUNDS = '/refunds';
const PUBLIC_ROUTE_PAGE_SHOP = '/shop';

export {
  PUBLIC_ROUTE_PAGE_ABOUT,
  PUBLIC_ROUTE_PAGE_AUTHENTICATE,
  PUBLIC_ROUTE_PAGE_COOKIES,
  PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORS,
  PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORSLIZARDSPOCK,
  PUBLIC_ROUTE_PAGE_JOB_HUNTING_JAT,
  PUBLIC_ROUTE_PAGE_HOME,
  PUBLIC_ROUTE_PAGE_PRICING,
  PUBLIC_ROUTE_PAGE_PRIVACY,
  PUBLIC_ROUTE_PAGE_REFUNDS,
  PUBLIC_ROUTE_PAGE_SHOP,
  PUBLIC_ROUTE_PAGE_TERMS,
};
