//  affiliate links
const PUBLIC_ROUTE_PAGE_COURSE_HELLO_CODING_ANYONE_CAN_LEARN_TO_CODE =
  '/affiliate/courses/hello-coding-anyone-can-learn-to-code';
//  apps
const PUBLIC_ROUTE_PAGE_APPS_FELONY_CHARGES_DJT =
  '/apps/felony-charges-of-donald-j-trump';
const PUBLIC_ROUTE_PAGE_APPS_JOB_HUNTING_JAT = '/apps/job-application-tracking';
const PUBLIC_ROUTE_PAGE_APPS_TO_DO = '/apps/to-do';
//  games
const PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORS = '/games/rock-paper-scissors';
const PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORSLIZARDSPOCK =
  '/games/rock-paper-scissors-lizard-spock';
//  legal
const PUBLIC_ROUTE_PAGE_COOKIES = '/legal/cookies';
const PUBLIC_ROUTE_PAGE_PRIVACY = '/legal/privacy';
const PUBLIC_ROUTE_PAGE_TERMS = '/legal/terms';
//  root
const PUBLIC_ROUTE_PAGE_ABOUT = '/about';
const PUBLIC_ROUTE_PAGE_AUTHENTICATE = '/authenticate';
const PUBLIC_ROUTE_PAGE_FELONY_CHARGES_DJT =
  '/felony-charges-of-donald-j-trump';
const PUBLIC_ROUTE_PAGE_HOME = '/';
const PUBLIC_ROUTE_PAGE_PRICING = '/pricing';
const PUBLIC_ROUTE_PAGE_REFUNDS = '/refunds';
const PUBLIC_ROUTE_PAGE_SHOP = '/shop';
const PUBLIC_ROUTE_PAGE_TIKTOKBIO = '/tik-tok-bio';
const PUBLIC_ROUTE_PAGE_TUTORIALS = '/tutorials';
const PUBLIC_ROUTE_PAGE_TUTORIALS_APP_TODO = `${PUBLIC_ROUTE_PAGE_TUTORIALS}/to-do`;
const PUBLIC_ROUTE_PAGE_TUTORIALS_GAME_ROCK_PAPER_SCISSORS = `${PUBLIC_ROUTE_PAGE_TUTORIALS}/rock-paper-scissors`;

export {
  PUBLIC_ROUTE_PAGE_COURSE_HELLO_CODING_ANYONE_CAN_LEARN_TO_CODE,
  PUBLIC_ROUTE_PAGE_ABOUT,
  PUBLIC_ROUTE_PAGE_APPS_FELONY_CHARGES_DJT,
  PUBLIC_ROUTE_PAGE_APPS_JOB_HUNTING_JAT,
  PUBLIC_ROUTE_PAGE_APPS_TO_DO,
  PUBLIC_ROUTE_PAGE_AUTHENTICATE,
  PUBLIC_ROUTE_PAGE_COOKIES,
  PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORS,
  PUBLIC_ROUTE_PAGE_GAMES_ROCKPAPERSCISSORSLIZARDSPOCK,
  PUBLIC_ROUTE_PAGE_FELONY_CHARGES_DJT,
  PUBLIC_ROUTE_PAGE_HOME,
  PUBLIC_ROUTE_PAGE_PRICING,
  PUBLIC_ROUTE_PAGE_PRIVACY,
  PUBLIC_ROUTE_PAGE_REFUNDS,
  PUBLIC_ROUTE_PAGE_SHOP,
  PUBLIC_ROUTE_PAGE_TERMS,
  PUBLIC_ROUTE_PAGE_TIKTOKBIO,
  PUBLIC_ROUTE_PAGE_TUTORIALS,
  PUBLIC_ROUTE_PAGE_TUTORIALS_APP_TODO,
  PUBLIC_ROUTE_PAGE_TUTORIALS_GAME_ROCK_PAPER_SCISSORS,
};
