const SORT_BY_COLUMN_ALPHANUMERIC = 'alphanumeric';
const SORT_BY_COLUMN_CHARACTER = 'character';
const SORT_BY_COLUMN_UNICODE = 'unicode';
const SORT_BY_COLUMN_TYPE = 'type';

const SORT_BY_ORDER_ASCENDING = 'ascending';
const SORT_BY_ORDER_DESCENDING = 'descending';

export {
  SORT_BY_COLUMN_ALPHANUMERIC,
  SORT_BY_COLUMN_CHARACTER,
  SORT_BY_COLUMN_TYPE,
  SORT_BY_COLUMN_UNICODE,
  SORT_BY_ORDER_ASCENDING,
  SORT_BY_ORDER_DESCENDING,
};
