const DATA_SET_SORT_STEP_SORT = 'sort';
const DATA_SET_SORT_STEP_ENTITIES = 'entities'; //  default
const DATA_SET_SORT_STEP_FOOTNOTE_VALUES = 'footnote-values';
const DATA_SET_SORT_STEP_COMPLETE = 'complete';

const SORT_BY_COLUMN_ALPHANUMERIC = 'alphanumeric';
const SORT_BY_COLUMN_CHARACTER = 'character';
const SORT_BY_COLUMN_UNICODE = 'unicode';
const SORT_BY_COLUMN_TYPE = 'type';

const SORT_BY_ORDER_ASCENDING = 'ascending';
const SORT_BY_ORDER_DESCENDING = 'descending';

export {
  DATA_SET_SORT_STEP_SORT,
  DATA_SET_SORT_STEP_ENTITIES,
  DATA_SET_SORT_STEP_FOOTNOTE_VALUES,
  DATA_SET_SORT_STEP_COMPLETE,

  SORT_BY_COLUMN_ALPHANUMERIC,
  SORT_BY_COLUMN_CHARACTER,
  SORT_BY_COLUMN_TYPE,
  SORT_BY_COLUMN_UNICODE,
  SORT_BY_ORDER_ASCENDING,
  SORT_BY_ORDER_DESCENDING,
};
