const FORM_INPUT_WORD_COUNT = 150;
const FORM_INPUT_WORD_MAX = 1000;
const FORM_INPUT_WORD_MIN = 0;
const FORM_INPUT_WORD_STEP = 10;

export {
  FORM_INPUT_WORD_COUNT,
  FORM_INPUT_WORD_MAX,
  FORM_INPUT_WORD_MIN,
  FORM_INPUT_WORD_STEP,
};
