const FORM_INPUT_TONE_CASUAL = 'casual';
const FORM_INPUT_TONE_FORMAL = 'formal';
const FORM_INPUT_TONE_FRIENDLY = 'friendly';
const FORM_INPUT_TONE_NEUTRAL = 'neutral';
const FORM_INPUT_TONE_PROFESSIONAL = 'professional';

export {
  FORM_INPUT_TONE_CASUAL,
  FORM_INPUT_TONE_FORMAL,
  FORM_INPUT_TONE_FRIENDLY,
  FORM_INPUT_TONE_NEUTRAL,
  FORM_INPUT_TONE_PROFESSIONAL,
};
