import { FORM_INPUT_KEYWORDS_ROWS } from './form-keywords';

import {
  FORM_INPUT_TONE_CASUAL,
  FORM_INPUT_TONE_FORMAL,
  FORM_INPUT_TONE_FRIENDLY,
  FORM_INPUT_TONE_NEUTRAL,
  FORM_INPUT_TONE_PROFESSIONAL,
} from './form-tone';

import {
  FORM_INPUT_WORD_COUNT,
  FORM_INPUT_WORD_MAX,
  FORM_INPUT_WORD_MIN,
  FORM_INPUT_WORD_STEP,
} from './form-word-count';

export {
  FORM_INPUT_KEYWORDS_ROWS,
  FORM_INPUT_TONE_CASUAL,
  FORM_INPUT_TONE_FORMAL,
  FORM_INPUT_TONE_FRIENDLY,
  FORM_INPUT_TONE_NEUTRAL,
  FORM_INPUT_TONE_PROFESSIONAL,
  FORM_INPUT_WORD_COUNT,
  FORM_INPUT_WORD_MAX,
  FORM_INPUT_WORD_MIN,
  FORM_INPUT_WORD_STEP,
};
